default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: td7_freelancer_project_development

test:
  <<: *default
  database: td7_freelancer_project_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: td7_freelancer_project_production
  username: td7_freelancer_project
  password: <%= ENV['TD7_FREELANCER_PROJECT_DATABASE_PASSWORD'] %>
